### ISSUE TITLE
Internal Server Error: ownCloud 8.1.0.8 & grauphel 0.5.1: UrlGenerator: Escaping Problem?

### ISSUE THREAD

**Issue by lars-becker** [cweiske/grauphel#22]
Hi Christian,

I just installed grauphel, synced some notes and tried to access grauphel from within OwnCloud. I got an internal server error; seemingly because some problem with the Symfony UrlGenerator. It looks to me that it might be a problem with the escaping. 

Here is the relevant part of the log:

```
Technische Details

    Entfernte Adresse: x.x.x.x
    Anforderungskennung: xxx/xxxx
    Typ: Symfony\Component\Routing\Exception\InvalidParameterException
    Code: 0
    Nachricht: Parameter "rawtag" for route "grauphel.gui.tag" must match "[^/]++" ("system:notebook:Kultur / Feuilleton" given) to generate a corresponding URL.
    Datei: /var/www/owncloud/3rdparty/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php
    Zeile: 167


Spur

#0 /var/www/owncloud/3rdparty/symfony/routing/Symfony/Component/Routing/Generator/UrlGenerator.php(140): Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'grauphel.gui.ta...', false, Array, Array)
#1 /var/www/owncloud/lib/private/route/router.php(306): Symfony\Component\Routing\Generator\UrlGenerator->generate('grauphel.gui.ta...', Array, false)
#2 /var/www/owncloud/lib/private/urlgenerator.php(65): OC\Route\Router->generate('grauphel.gui.ta...', Array)
#3 /var/www/owncloud/apps/grauphel/controller/guicontroller.php(292): OC\URLGenerator->linkToRoute('grauphel.gui.ta...', Array)
[...]
```

**Comment by cweiske** [comment]
I've never had a `/` in a tag; that's the issue we're facing here.
I'll fix that problem.

**Comment by cweiske** [comment]
Will be in the next release.

**Comment by lars-becker** [comment]
Thanks a lot! :)
