### ISSUE TITLE
Syncing Tomdroid with grauphel on nextcloud 11

### ISSUE THREAD

**Issue by JoBilert** [cweiske/grauphel#46]
I installed grauphel on my nextcloud 11 (running on an armbian system).
Installation went fine and when i pointed my TomDroid to the server I could authenticate and everything.
But whenever I try to sync, I get an error-message:

> Fehler beim Verarbeiten der Antwort von Online-Synchronisation
(Sorry don't know the English version of that message)

Do you have any idea where that comes from?

**Comment by cweiske** [comment]
I've personally not seen this message before.

There are several things you could inspect:

1. Your web server error logs and check if anything relevant is logged in there.
2. Connect your android phone via usb to your computer, and get the tomdroid logs via `adb`. This is quite hard for non-techies to setup, so it's ok if you choose not to do that.
3. Try synchronization with Tomboy and see if that works.

**Comment by bastei** [comment]
Same problem. Here are the logs of an authentication process (hopefully I did't clean important parts away).

adb log:
```
3511  3511 I Tomdroid: Creating dialog
3511  4599 I WebConnection: Sending http-header: X-Tomboy-Client: org.tomdroid v0.7.5, build 14, Android v7.1.1
3511  4599 I WebConnection: Response status : HTTP/1.1 200 OK
3511  4599 I WebConnection: Received : {"oauth_request_token_url":"https:\/\/domain.tld\/apps\/grauphel\/oauth\/request_token","oauth_authorize_url":"https:\/\/domain.tld\/apps\/grauphel\/oauth\/authorize?client=org.tomdroid+v0.7.5%2C+build+14%2C+Android+v7.1.1","oauth_access_token_url":"https:\/\/domain.tld\/apps\/grauphel\/oauth\/access_token","api-version":"1.0"}
3511  4599 I OAuthConnection: Authorization URL : https://domain.tld/apps/grauphel/oauth/authorize?client=org.tomdroid+v0.7.5%2C+build+14%2C+Android+v7.1.1&oauth_token=r47a74d31271670b6
1799  2552 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://domain.tld/... cmp=android/com.android.internal.app.ResolverActivity} from uid 10103 on display 0
1799  1909 I ActivityManager: Start proc 4610:system:ui/1000 for activity android/com.android.internal.app.ResolverActivity
1799  1822 I ActivityManager: Displayed android/com.android.internal.app.ResolverActivity: +451ms
1799  2588 I PackageManager: Setting last chosen activity acr.browser.lightning/.activity.MainActivity for user 0:
1799  2588 I PackageManager:   Action: "android.intent.action.VIEW"
1799  2588 I PackageManager:   Category: "android.intent.category.DEFAULT"
1799  2588 I PackageManager:   Scheme: "https"
1799  2588 I PackageManager:   AutoVerify=false
1799  1909 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=https://domain.tld/... flg=0x3000000 cmp=acr.browser.lightning/.activity.MainActivity} from uid 10103 on display 0
1799  2106 I ActivityManager: Start proc 4650:acr.browser.lightning/u0a84 for activity acr.browser.lightning/.activity.MainActivity
1799  2552 I ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=tomdroid://sync?oauth_token=r47a74d31271670b6&oauth_verifier=v89de3177306eabc7 cmp=org.tomdroid/.ui.Tomdroid (has extras)} from uid 10084 on display 0
3511  3511 I Tomdroid: Got url : tomdroid://sync?oauth_token=r47a74d31271670b6&oauth_verifier=v89de3177306eabc7
3511  4836 I OAuthConnection: Verifier: v89de3177306eabc7
1799  1822 I ActivityManager: Displayed org.tomdroid/.ui.Tomdroid: +467ms
1799  1898 D ConnectivityService: NetworkAgentInfo [WIFI () - 103] validation failed
3511  4836 I WebConnection: Sending http-header: X-Tomboy-Client: org.tomdroid v0.7.5, build 14, Android v7.1.1
3511  4836 W DefaultRequestDirector: Authentication error: Unable to respond to any of these challenges: {}
3511  4836 I WebConnection: Response status : HTTP/1.1 401 Unauthorized
3511  4836 I WebConnection: Received : oauth_problem=signature_invalid&debug_sbs=GET&https%3A%2F%2Fdomain.tld%2Fapps%2Fgrauphel%2Fapi%2F1.0%2F&oauth_consumer_key%3Danyone%26oauth_nonce%3D-8531961789669900049%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1489024040%26oauth_token%3Da5166a0fbe91dec1f%26oauth_verifier%3Dv89de3177306eabc7%26oauth_version%3D1.0
3511  4836 W System.err: org.json.JSONException: Value oauth_problem of type java.lang.String cannot be converted to JSONObject
3511  4836 W System.err: 	at org.json.JSON.typeMismatch(JSON.java:111)
3511  4836 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:160)
3511  4836 W System.err: 	at org.json.JSONObject.<init>(JSONObject.java:173)
3511  4836 W System.err: 	at org.tomdroid.sync.web.OAuthConnection.getAccess(OAuthConnection.java:219)
3511  4836 W System.err: 	at org.tomdroid.sync.web.SnowySyncService$2.run(SnowySyncService.java:130)
3511  4836 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
3511  4836 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
3511  4836 W System.err: 	at java.lang.Thread.run(Thread.java:761)
3511  4836 I OAuthConnection: Got access token a5166a0fbe91dec1f.
3511  4836 I SnowySyncService: The authorization process is complete.
3511  4847 W System.err: oauth.signpost.exception.OAuthMessageSignerException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
3511  4847 W System.err: 	at oauth.signpost.signature.SignatureBaseString.generate(SignatureBaseString.java:60)
3511  4847 W System.err: 	at oauth.signpost.signature.HmacSha1MessageSigner.sign(HmacSha1MessageSigner.java:51)
3511  4847 W System.err: 	at oauth.signpost.AbstractOAuthConsumer.sign(AbstractOAuthConsumer.java:109)
3511  4847 W System.err: 	at oauth.signpost.AbstractOAuthConsumer.sign(AbstractOAuthConsumer.java:120)
3511  4847 W System.err: 	at org.tomdroid.sync.web.OAuthConnection.sign(OAuthConnection.java:109)
3511  4847 W System.err: 	at org.tomdroid.sync.web.OAuthConnection.get(OAuthConnection.java:242)
3511  4847 W System.err: 	at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:182)
3511  4847 W System.err: 	at org.tomdroid.sync.SyncService$1.run(SyncService.java:170)
3511  4847 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
3511  4847 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
3511  4847 W System.err: 	at java.lang.Thread.run(Thread.java:761)
3511  4847 W System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
3511  4847 W System.err: 	at oauth.signpost.signature.SignatureBaseString.normalizeRequestUrl(SignatureBaseString.java:66)
3511  4847 W System.err: 	at oauth.signpost.signature.SignatureBaseString.generate(SignatureBaseString.java:54)
3511  4847 W System.err: 	... 10 more
3511  4847 I WebConnection: Sending http-header: X-Tomboy-Client: org.tomdroid v0.7.5, build 14, Android v7.1.1
3511  4847 W System.err: java.lang.IllegalStateException: Target host must not be null, or set in parameters. scheme=null, host=null, path=
3511  4847 W System.err: 	at org.apache.http.impl.client.DefaultRequestDirector.determineRoute(DefaultRequestDirector.java:605)
3511  4847 W System.err: 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:299)
3511  4847 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
3511  4847 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
3511  4847 W System.err: 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
3511  4847 W System.err: 	at org.tomdroid.sync.web.WebConnection.execute(WebConnection.java:124)
3511  4847 W System.err: 	at org.tomdroid.sync.web.OAuthConnection.get(OAuthConnection.java:243)
3511  4847 W System.err: 	at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:182)
3511  4847 W System.err: 	at org.tomdroid.sync.SyncService$1.run(SyncService.java:170)
3511  4847 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
3511  4847 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
3511  4847 W System.err: 	at java.lang.Thread.run(Thread.java:761)
3511  4847 E SnowySyncService: Problem parsing the server response
3511  4847 E SnowySyncService: org.json.JSONException: End of input at character 0 of 
3511  4847 E SnowySyncService: 	at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
3511  4847 E SnowySyncService: 	at org.json.JSONTokener.nextValue(JSONTokener.java:97)
3511  4847 E SnowySyncService: 	at org.json.JSONObject.<init>(JSONObject.java:156)
3511  4847 E SnowySyncService: 	at org.json.JSONObject.<init>(JSONObject.java:173)
3511  4847 E SnowySyncService: 	at org.tomdroid.sync.web.SnowySyncService$3.run(SnowySyncService.java:196)
3511  4847 E SnowySyncService: 	at org.tomdroid.sync.SyncService$1.run(SyncService.java:170)
3511  4847 E SnowySyncService: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
3511  4847 E SnowySyncService: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
3511  4847 E SnowySyncService: 	at java.lang.Thread.run(Thread.java:761)
```

Server log:
```
"GET /index.php/apps/grauphel/api/1.0/ HTTP/1.1" 200 372 "-"
"POST /apps/grauphel/oauth/request_token HTTP/1.1" 200 96 "-"
"GET /apps/grauphel/oauth/authorize?client=org.tomdroid+v0.7.5%2C+build+14%2C+Android+v7.1.1&oauth_token=r47a74d31271670b6 HTTP/1.1" 303 5 "Mozilla/5.0 (Linux; U; Android 4.4) AppleWebKit/534.30"
"GET /login?redirect_url=/apps/grauphel/oauth/authorize%3Fclient%3Dorg.tomdroid%2Bv0.7.5%252C%2Bbuild%2B14%252C%2BAndroid%2Bv7.1.1%26oauth_token%3Dr47a74d31271670b6 HTTP/1.1" 200 18022 "Mozilla/5.0 (Linux; U; Android 4.4) AppleWebKit/534.30"
"POST /login?redirect_url=/apps/grauphel/oauth/authorize%3Fclient%3Dorg.tomdroid%2Bv0.7.5%252C%2Bbuild%2B14%252C%2BAndroid%2Bv7.1.1%26oauth_token%3Dr47a74d31271670b6 HTTP/1.1" 303 5 "Mozilla/5.0 (Linux; U; Android 4.4) AppleWebKit/534.30"
"GET /apps/grauphel/oauth/authorize?client=org.tomdroid%20v0.7.5,%20build%2014,%20Android%20v7.1.1&oauth_token=r47a74d31271670b6 HTTP/1.1" 200 25055 "Mozilla/5.0 (Linux; U; Android 4.4) AppleWebKit/534.30"
"POST /apps/grauphel/oauth/confirm HTTP/1.1" 303 5 "Mozilla/5.0 (Linux; U; Android 4.4) AppleWebKit/534.30"
"POST /apps/grauphel/oauth/access_token HTTP/1.1" 200 66 "-"
"GET /index.php/apps/grauphel/api/1.0/ HTTP/1.1" 401 350 "-"
```

**Comment by cweiske** [comment]
@TalmarGrosskotz: Which Android and Tomdroid version are you using?

@bastei: Is your server also running on an ARM CPU?

**Comment by bastei** [comment]
No, the server is running Debian Jessie on x86 architecture.

**Comment by cultcom** [comment]
I have the same issue after upgrading my debian 8 to debian 9 with php 7.0-fpm. The clients which could sync before are now getting 401 unauth responses:

```
[ERROR 11:42:13.083] Caught exception. Message: The remote server returned an error: (401) Unauthorized.
[ERROR 11:42:13.084] Stack trace for previous exception:   at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x4158fe30 + 0x001ab> in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () <0x4158c2f0 + 0x0005a> in <filename unknown>:0 
  at Tomboy.WebSync.Api.OAuth.MakeWebRequest (RequestMethod method, System.String url, System.Collections.Generic.List`1 parameters, System.String postData) <0x4156c5a0 + 0x00376> in <filename unknown>:0 
[ERROR 11:42:13.085] Rest of stack trace for above exception:   at System.Environment.get_StackTrace () [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.Api.OAuth.MakeWebRequest (RequestMethod method, System.String url, System.Collections.Generic.List`1 parameters, System.String postData) [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.Api.OAuth.WebRequest (RequestMethod method, System.String url, System.String postData) [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.Api.OAuth.Get (System.String uri, IDictionary`2 queryParameters) [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.Api.RootInfo.GetRoot (System.String rootUri, IWebConnection connection) [0x00000] in <filename unknown>:0 
  at Tomboy.WebSync.WebSyncServer.BeginSyncTransaction () [0x00000] in <filename unknown>:0 
  at Tomboy.Sync.SyncManager.SynchronizationThread () [0x00000] in <filename unknown>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <filename unknown>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) [0x00000] in <filename unknown>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) [0x00000] in <filename unknown>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <filename unknown>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00000] in <filename unknown>:0 
[ERROR 11:42:13.085] Synchronization failed with the following exception: The remote server returned an error: (401) Unauthorized.
  at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x4158fe30 + 0x001ab> in <filename unknown>:0 
  at System.Net.HttpWebRequest.GetResponse () <0x4158c2f0 + 0x0005a> in <filename unknown>:0 
  at Tomboy.WebSync.Api.OAuth.MakeWebRequest (RequestMethod method, System.String url, System.Collections.Generic.List`1 parameters, System.String postData) <0x4156c5a0 + 0x00376> in <filename unknown>:0 
```
I am running nextcloud 11 with the following software versions:
```
ii  apache2                           2.4.25-3+deb9u2                amd64        Apache HTTP Server
ii  php-oauth                         2.0.2+1.2.3-1                  amd64        OAuth 1.0 consumer and provider extension
ii  php7.0-fpm                        7.0.19-1                       amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
```

**Comment by mwerle** [comment]
Just FYI, in the process of installing a new VPS using Debian 9 "stretch" and slowly moving services across from my old server (Debian 8).  Part of the install I've completed involved upgrading from OwnCloud 8.1 to NextCloud 12.

Copied config and Grauphel to my new server, and it "just worked" (tm). Just tried it again to verify, and Tomdroid was able to sync successfully.

Running the same software versions as @cultcom , except it's NextCloud v12, not 11.

**Comment by cultcom** [comment]
Utilizing "ssldump" I could track this down a bit further.

After the upgrade to Debian "stretch" and nextCloud 11 and now 12 the API URL to grauphel changed in a way that the "index.php" part is no longer used.

This leads to a signature error in oauth and the clients fail to sync.

A solution for me was to fix all my clients to the new, shorter URL and connect them again. Now it works fine like it used to do before the upgrade.

Old:
```
https://example.net/index.php/apps/grauphel
```
New:
```
https://example.net/apps/grauphel
```

**Comment by cweiske** [comment]
Documentation about pretty URLs in nextcloud:
- https://docs.nextcloud.com/server/11/admin_manual/installation/source_installation.html#pretty-urls
- https://github.com/nextcloud/documentation/issues/54

I think that this is the most probable explanation @TalmarGrosskotz. I'm closing this now.
